### ISSUE TITLE
Prediction

### ISSUE THREAD

**Issue by Zumbalamambo** [beader/tianchi-fashionai#1]
Everytime when i do prediction, should I pass the category number manually by myself?

**Comment by beader** [comment]
@Zumbalamambo Yes, because category number will be used as an embedding layer in this structure. All categories are using the same network and the embedding layer may be treated as a kind of attention mechanism.

**Comment by Zumbalamambo** [comment]
sometimes when i do prediction with my own data , the mode is overfitting. it works on the dataset which was used as a training samples but not in the testing samples...do you have any idea why is that so?

**Comment by beader** [comment]
It is just a baseline model without carefully fine-tuning yet. Also It is not a state-of-the-art architecture.
